#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Installation and Setup Script for Vi-S1K System
Cài đặt và thiết lập hệ thống Vi-S1K
"""

import os
import sys
import subprocess
import io
from pathlib import Path

# Fix encoding for Windows
if sys.stdout.encoding != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')


def print_section(title):
    """In tiêu đề section"""
    print("\n" + "=" * 70)
    print(f"  {title}")
    print("=" * 70)


def run_command(cmd, description):
    """Chạy command và báo kết quả"""
    print(f"\n▶ {description}")
    print(f"  $ {cmd}")
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            print(f"  ✓ Success")
            return True
        else:
            print(f"  ✗ Failed")
            if result.stderr:
                print(f"  Error: {result.stderr[:200]}")
            return False
    except Exception as e:
        print(f"  ✗ Error: {e}")
        return False


def install_dependencies():
    """Cài đặt dependencies"""
    print_section("1. CÀI ĐẶT DEPENDENCIES")
    
    packages = [
        "datasets",
        "transformers",
        "torch",
        "google-generativeai",
        "openai",
        "pandas",
        "tqdm",
        "python-dotenv",
        "nltk"
    ]
    
    print("\nCác packages cần cài đặt:")
    for pkg in packages:
        print(f"  • {pkg}")
    
    choice = input("\nCài đặt tất cả packages? (y/n): ").strip().lower()
    
    if choice == 'y':
        for pkg in packages:
            run_command(f"pip install {pkg}", f"Installing {pkg}")
    else:
        print("\nBỏ qua cài đặt packages")


def create_env_file():
    """Tạo file .env"""
    print_section("2. THIẾT LẬP API KEYS")
    
    env_path = Path(".env")
    
    if env_path.exists():
        choice = input("\nFile .env đã tồn tại. Ghi đè? (y/n): ").strip().lower()
        if choice != 'y':
            return
    
    print("\nNhập API keys (để trống để bỏ qua):")
    
    gemini_key = input("  Google Gemini API Key: ").strip()
    openai_key = input("  OpenAI API Key: ").strip()
    hf_token = input("  Hugging Face Token: ").strip()
    
    env_content = f"""# Vi-S1K Configuration
# Generated by setup script

# Google Gemini API
GEMINI_API_KEY={gemini_key}

# OpenAI API
OPENAI_API_KEY={openai_key}

# Hugging Face Token (for dataset loading)
HF_TOKEN={hf_token}

# Local model paths (if using local models)
# LOCAL_MODEL_PATH=./models/llama2
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"\n✓ Tạo file .env thành công")


def setup_directories():
    """Tạo các thư mục cần thiết"""
    print_section("3. TẠO CẤU TRÚC THƯỤC MỤC")
    
    directories = [
        "./results/vi_s1k",
        "./results/vi_s1k_test",
        "./translation_cache",
        "./models",
        "./data",
        "./logs"
    ]
    
    print("\nTạo thư mục:")
    for directory in directories:
        Path(directory).mkdir(parents=True, exist_ok=True)
        print(f"  ✓ {directory}")


def verify_installation():
    """Kiểm tra cài đặt"""
    print_section("4. KIỂM TRA CÀI ĐẶT")
    
    checks = {
        "Python version": lambda: sys.version.split()[0],
        "datasets": lambda: __import__("datasets").__version__,
        "transformers": lambda: __import__("transformers").__version__,
        "Google Generative AI": lambda: __import__("google.generativeai").__version__,
    }
    
    print("\nKiểm tra packages:")
    for name, checker in checks.items():
        try:
            version = checker()
            print(f"  ✓ {name:25s} - v{version}")
        except Exception as e:
            print(f"  ✗ {name:25s} - Not installed")
    
    # Kiểm tra .env file
    if Path(".env").exists():
        print(f"  ✓ {'Config file (.env)':25s} - Found")
    else:
        print(f"  ⚠ {'Config file (.env)':25s} - Not found")
    
    # Kiểm tra thư mục
    print("\nKiểm tra thư mục:")
    for directory in ["./results", "./translation_cache"]:
        if Path(directory).exists():
            print(f"  ✓ {directory}")
        else:
            print(f"  ✗ {directory}")


def download_sample_data():
    """Download dữ liệu mẫu"""
    print_section("5. DOWNLOAD DỮ LIỆU MẪU (TỰY CHỌN)")
    
    print("""
Hệ thống Vi-S1K sẽ tự động tải dataset S1K từ Hugging Face
khi bạn chạy lần đầu tiên.

Để tải sẵn (optional):
  python -c "from datasets import load_dataset; load_dataset('simplescaling/s1K-1.1')"
    """)
    
    choice = input("Tải dữ liệu mẫu ngay? (y/n): ").strip().lower()
    if choice == 'y':
        print("\nTải S1K dataset... (có thể mất vài phút)")
        try:
            from datasets import load_dataset
            load_dataset("simplescaling/s1K-1.1")
            print("✓ Dataset tải thành công")
        except Exception as e:
            print(f"✗ Tải thất bại: {e}")


def test_translator():
    """Test translator"""
    print_section("6. TEST TRANSLATOR (TỰY CHỌN)")
    
    choice = input("\nChạy translator test? (y/n): ").strip().lower()
    if choice != 'y':
        return
    
    try:
        sys.path.insert(0, str(Path(__file__).parent.parent / "llm_evaluation"))
        from llm_evaluation.utils.translation_utils import get_translator
        
        print("\nKhởi tạo translator...")
        translator = get_translator("gemini")
        
        print("Dịch câu test...")
        result = translator.translate("What is 2 + 2?", "English", "Vietnamese", "mathematics")
        
        print(f"\nTest result:")
        print(f"  English: What is 2 + 2?")
        print(f"  Vietnamese: {result}")
        print("\n✓ Translator hoạt động bình thường")
    
    except Exception as e:
        print(f"\n✗ Translator test failed: {e}")


def show_next_steps():
    """Hiển thị các bước tiếp theo"""
    print_section("BƯỚC TIẾP THEO")
    
    print("""
Cài đặt hoàn tất! Bước tiếp theo:

1. Chạy demo:
   python generates/quickstart_vi_s1k.py

2. Xem ví dụ chi tiết:
   python generates/examples_vi_s1k.py

3. Dịch dataset:
   python generates/vi_s1k_builder.py --translator gemini --test-run

4. Xem tài liệu đầy đủ:
   generates/README_VI_S1K.md

5. Tích hợp với LLM Evaluator:
   python llm_evaluation/main.py --questions-file results/vi_s1k/vi_s1k_benchmark.json

Cần giúp đỡ?
- Xem README: generates/README_VI_S1K.md
- Chạy examples: python generates/examples_vi_s1k.py
- Kiểm tra logs: ./logs/
    """)


def main():
    """Main installation flow"""
    
    print("""
╔════════════════════════════════════════════════════════════╗
║                                                            ║
║          Vi-S1K Installation & Setup Script                ║
║                                                            ║
║   Vietnamese S1K Benchmark Translation System              ║
║                                                            ║
╚════════════════════════════════════════════════════════════╝
    """)
    
    # 1. Cài đặt dependencies
    install_dependencies()
    
    # 2. Thiết lập API keys
    setup_choice = input("\nThiết lập API keys? (y/n): ").strip().lower()
    if setup_choice == 'y':
        create_env_file()
    
    # 3. Tạo thư mục
    setup_directories()
    
    # 4. Kiểm tra cài đặt
    verify_installation()
    
    # 5. Download dữ liệu mẫu
    download_choice = input("\nTải dữ liệu mẫu? (y/n): ").strip().lower()
    if download_choice == 'y':
        download_sample_data()
    
    # 6. Test translator
    test_choice = input("\nTest translator? (y/n): ").strip().lower()
    if test_choice == 'y':
        test_translator()
    
    # 7. Hiển thị next steps
    show_next_steps()
    
    print("\n" + "=" * 70)
    print("  Cài đặt hoàn tất! 🎉")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nCài đặt bị hủy bỏ")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n✗ Lỗi: {e}")
        sys.exit(1)
